import { getRandomExitLine, getRandomRestartLine, createExitNode, createRestartMarker } from './dialogueHelpers';

const exitNode = createExitNode();
const restartMarker = createRestartMarker();

// Branch 1: 8 choices (root→2→3→4→5→6→7→8→9)
const d1_9a = { text: "Yeah. Masc when it suits me. Some days I wake up and I'm feeling more masculine, so I dress that way, act that way. Other days, not so much. I just go with whatever feels right in the moment. It's not complicated. I don't overthink it. Just...masc when it suits me, you know?", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_9b = { text: "Exactly. I choose how I show up. Nobody else gets to decide that for me. If I want to be masc today, I'm masc. If I don't, I'm not. It's my choice. My presentation, my decision. And that feels good, honestly. Having that freedom to just...be whatever I am on any given day.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_8a = { text: "Sometimes masc, sometimes not. It's fluid, yeah. I don't have one fixed way of being. Some days I lean more masculine—flannel, boots, that whole vibe. Other days I'm more neutral, more whatever. It shifts. And that fluidity works for me. I don't need to be one thing all the time.", speaker: "D.", choices: [{ text: "You move between?", next: d1_9a }, { text: "That sounds freeing.", next: d1_9b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_9c = { text: "I just do what feels right. Wake up, see how I'm feeling, dress accordingly. Go about my day. I don't plan it out or think too hard about it. Just...what feels right? That's what I do. Simple as that. Works for me.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_9d = { text: "Yeah. No rules, just vibes. That's kind of my whole approach to life, honestly. I don't like rules. Don't like being told how to be or what to do. So I just...vibe. Do what feels natural. And it works out. Life's easier that way.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_8b = { text: "I don't think about it too much honestly. Some people spend a lot of time planning their presentation, thinking about what it means. Not me. I just wake up and...exist. Wear what's comfortable. Do what feels natural. Don't overthink it. Overthinking just complicates things.", speaker: "D.", choices: [{ text: "You follow your gut?", next: d1_9c }, { text: "Intuitive presentation?", next: d1_9d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_7a = { text: "Sometimes I feel masc, sometimes I don't. It's not consistent. Some days I wake up and masculinity feels right. I want to dress in work clothes, move through the world in that masculine way. Other days, not so much. Other days I'm just...neutral. Just me. No particular gender to it. It changes.", speaker: "D.", choices: [{ text: "Does it change day to day?", next: d1_8a }, { text: "Do you plan it?", next: d1_8b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_9e = { text: "Not really. I just am. I don't need labels to exist. I can just...be. Whatever I am in any given moment, that's what I am. I don't need to name it or define it or explain it. I just exist. And that's enough for me.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_9f = { text: "Yeah. Why box myself in? Labels are limiting, you know? They try to fit you into these narrow categories. And I don't fit into categories. I just am. So why would I choose a box when I could just...not? Freedom in not choosing. Exactly.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_8c = { text: "I don't really identify strongly with anything. People are always trying to label themselves, figure out what they are. And that's fine for them. But me? I don't feel a strong pull toward any particular identity. I'm just...me. Whatever that is. And that's comfortable. Not needing to define it.", speaker: "D.", choices: [{ text: "Does that feel comfortable?", next: d1_9e }, { text: "Freedom in not choosing?", next: d1_9f }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_9g = { text: "Definitely. I like the ambiguity. When people can't quite figure me out—is that person masc? Femme? Neither? Both?—I like that. Ambiguity means freedom. Means I'm not locked into one thing. People can wonder. I don't mind. I kind of enjoy it, actually.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_9h = { text: "Yeah. I don't owe anyone certainty. People want you to be clear, to fit into categories they understand. But I don't owe them that. I can be ambiguous. I can be undefined. That's my right. If it makes people uncomfortable, that's their problem, not mine.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_8d = { text: "I like keeping people guessing. There's something fun about being unreadable. When people can't immediately categorize me, can't put me in a box—that's when I feel most free. Most myself. So yeah, I like the ambiguity. I cultivate it, even. On purpose.", speaker: "D.", choices: [{ text: "Intentional ambiguity?", next: d1_9g }, { text: "You resist categorization?", next: d1_9h }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_7b = { text: "I don't really use labels much. Never have. Labels feel limiting to me. Like once you pick one, you're stuck with it. You have to perform it. But I don't want to perform anything. I just want to be. So I skip the labels. Easier that way. Less pressure.", speaker: "D.", choices: [{ text: "Do labels feel limiting?", next: d1_8c }, { text: "You prefer flexibility?", next: d1_8d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_6a = { text: "Honestly? I just dress however feels right that day. I wake up, look at my closet, and grab whatever I'm drawn to. Some days that's flannel and work boots. Other days it's just jeans and a t-shirt. I don't plan it out. I don't think about what it means. I just...dress. And it works out fine.", speaker: "D.", choices: [{ text: "Does your gender shift?", next: d1_7a }, { text: "No fixed identity?", next: d1_7b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_9i = { text: "Work clothes, flannel, whatever's comfortable. I've got a pretty standard rotation. Jeans, flannels, work boots. Maybe a jacket when it's cold. Nothing fancy. Nothing that requires much thought. Just grab what's clean and comfortable and go. Practical stuff. That's my vibe.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_9j = { text: "Yeah. Comfort over everything. I'm not trying to make a statement with my clothes. I'm not trying to look a certain way. I just want to be comfortable. So I wear stuff that feels good, that I can move in, that doesn't require maintenance. Comfort first. Always.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_8e = { text: "Practical stuff. Functional. I wear things that work for my life—for work, for hiking, for just...existing. Nothing fancy. Nothing high-maintenance. Just clothes that do what they need to do. That's all I care about. Function over fashion.", speaker: "D.", choices: [{ text: "What do you wear?", next: d1_9i }, { text: "Comfort is key?", next: d1_9j }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_9k = { text: "Not particularly. I just exist. Some people think about gender a lot—what it means, how to express it, how it shapes their life. Not me. I just...am. Whatever I am, that's what I am. I don't need to analyze it or define it. I just exist and that's enough.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_9l = { text: "Yeah. I just do me. That's my whole philosophy, really. Just do me. Don't worry about what other people think, don't worry about fitting into categories. Just be myself. And that's worked out fine so far. No complaints.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_8f = { text: "I don't think about gender much. It's not something I spend time on. Some people are really focused on their gender, really intentional about it. Good for them. Me? I just...live. Gender's not a big part of how I see myself. It's just not that important to me.", speaker: "D.", choices: [{ text: "Does it not matter to you?", next: d1_9k }, { text: "You just live?", next: d1_9l }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_7c = { text: "I wear what's comfortable. That's my main criteria for clothes—does it feel good? Can I move in it? Is it practical? If yes, I wear it. If no, I don't. Simple as that. Comfort drives everything. Gender doesn't really factor into it.", speaker: "D.", choices: [{ text: "What's that look like?", next: d1_8e }, { text: "Is gender part of that?", next: d1_8f }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_9m = { text: "Sometimes. Not always. Some days leaning masc feels natural. I wake up and that's just where I'm at. Other days, not so much. It's not consistent. It shifts. And I'm fine with that. Don't need it to be the same all the time.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_9n = { text: "Yeah. When it suits me. When I feel like being masc, I lean into it. When I don't, I don't. It's a choice, but also...not? Like, it's a choice in the sense that I'm choosing to follow what feels right. But it's not like I'm forcing it. It's intuitive. Choice and instinct combined.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_8g = { text: "I lean masc sometimes. Not always, but sometimes. When I do, it's not a big deal. Just throw on some flannel, work boots, that kind of thing. Present more masculine. It feels natural when it happens. But it's not constant. Just...sometimes.", speaker: "D.", choices: [{ text: "Does it feel natural?", next: d1_9m }, { text: "Is it a choice?", next: d1_9n }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_9o = { text: "Not really. I just vibe. Wake up, see what I'm feeling, go with it. No planning. No strategizing. Just vibing through life. Seems to work out fine. Overthinking just complicates things. Better to just...vibe.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_9p = { text: "Yeah. Whatever feels right. That's my guide for pretty much everything. Does it feel right? Then I do it. Doesn't feel right? I don't. Simple. Intuitive. No overthinking required. Just...whatever feels right in the moment.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_8h = { text: "I don't overthink it. Some people plan out their whole presentation—what to wear, how to style themselves, what it all means. Too much work. I just wake up and do whatever feels right. No planning. Just intuition. Works fine for me.", speaker: "D.", choices: [{ text: "Do you plan your look?", next: d1_9o }, { text: "Intuitive?", next: d1_9p }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_7d = { text: "Masc presentation, when I want it. It's not my default or anything. Just something I do sometimes when it feels right. Throw on some work clothes, present more masculine. It's easy, comfortable. But it's not constant. Just when I want it. When it suits me.", speaker: "D.", choices: [{ text: "How often?", next: d1_8g }, { text: "How do you choose?", next: d1_8h }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_6b = { text: "Honestly? I just dress however. I don't have a particular style or aesthetic I'm going for. I just wear whatever I'm drawn to that day. Sometimes that's more masc, sometimes not. It varies. But I don't stress about it. Just...dress however. Simple.", speaker: "D.", choices: [{ text: "Tell me about your style.", next: d1_7c }, { text: "Do you present masc?", next: d1_7d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_5a = { text: "Masc presenting, I guess? That's how people would probably describe me if they had to. I wear work clothes, I move through the world in a more masculine way. But I don't think of it as 'masc presenting'—that's just...how I am. How I'm comfortable. I guess other people see it as masculine. And that's fine. Whatever.", speaker: "D.", choices: [{ text: "What does that mean to you?", next: d1_6a }, { text: "How do you describe your style?", next: d1_6b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_4a = { text: "I'm pretty fluid with presentation. Don't really stick to one thing. Some days more masc, some days less. It shifts based on mood, on feeling, on...I don't know, whatever. I don't analyze it. Just go with what feels right. That fluidity works for me. Don't see a reason to change it.", speaker: "D.", choices: [{ text: "Tell me about that.", next: d1_5a }, { text: "What does fluid mean for you?", next: d1_5a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_3a = { text: "Gender is whatever honestly. Like, it's not this big important thing to me. Some people make gender their whole identity. Good for them. Me? It's just...whatever. I exist. I wear what's comfortable. I do what feels right. Gender doesn't really factor into it. It's just not that deep for me.", speaker: "D.", choices: [{ text: "How so?", next: d1_4a }, { text: "You don't think about it much?", next: d1_4a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d1_2a = { text: "I'm not super into labels. Never have been. Labels feel restrictive, you know? Like once you pick one, you're stuck with it. You have to perform it. But I don't want to perform anything. I just want to live. So I skip the labels. Easier that way. Less pressure. Just...me.", speaker: "D.", choices: [{ text: "Why not?", next: d1_3a }, { text: "Tell me more.", next: d1_3a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };

// Branch 2: 8 choices
const d2_9a = { text: "Pretty much. I just live. Don't overthink where I am or why. Knoxville's home. I grew up here. My life is here. That's all there is to it. Some people move around, searching for something. Not me. I'm good here. Just...living.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_9b = { text: "Yeah. Life's easier that way. When you don't question everything, when you just accept where you are and live there—life's simpler. Less stress. I'm not searching for the perfect place. Knoxville's fine. It works. Why complicate it?", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_8a = { text: "I grew up here. It's just home. This is what I know. The mountains, the people, the vibe—it's all familiar. And familiar is comfortable. I'm not looking to leave. Not looking for something different. This is home. Simple as that.", speaker: "D.", choices: [{ text: "You don't question it?", next: d2_9a }, { text: "Comfortable here?", next: d2_9b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_9c = { text: "Not particularly. It's just where I am. Some people have deep feelings about their location—they love it or hate it, it shapes their whole identity. Me? Knoxville's just...where I live. It's fine. It works. That's about it. No deep feelings either way.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_9d = { text: "Yeah. It's fine. It's home. I'm not in love with Knoxville or anything. But I don't hate it either. It's just...home. Where my life is. Where my work is. Where the mountains are. It's fine. Good enough for me.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_8b = { text: "It's where I grew up. It's familiar. I know these streets, these mountains, these people. There's comfort in that familiarity. I'm not looking for adventure or change. I like knowing where I am, knowing what to expect. Familiar is good. Familiar works.", speaker: "D.", choices: [{ text: "Does it matter to you?", next: d2_9c }, { text: "Do you like it here?", next: d2_9d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_7a = { text: "Knoxville's just...where I am. It's not a big deal. Some people make location this huge part of their identity. Not me. I'm from Knoxville. I live in Knoxville. That's it. It doesn't define me. It's just geography. Just where I happen to be.", speaker: "D.", choices: [{ text: "How does it shape you?", next: d2_8a }, { text: "What's it like here?", next: d2_8b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_9e = { text: "I mean, some. Enough. I'm not super connected to the queer community here, but I know a few people. See them around sometimes. It's not like we're best friends or anything. Just...people I know. People who get it. That's enough for me. I don't need a huge community. Just a few folks who understand. That works.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_9f = { text: "Yeah. I know people. There's a small queer community here. Not huge, but it exists. I know some folks. See them at the coffee shop, at events sometimes. We're not super tight or anything. But there's community. Small but real. And that's fine. Good enough.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_8c = { text: "There's folks. Small but present. Knoxville's not a huge queer mecca or anything, but there are people. Queer bars, events, spaces. It's small. Scattered. But it's there. You can find people if you want to. I know a few folks. See them around. It's a small community, but it exists.", speaker: "D.", choices: [{ text: "Do you connect with them?", next: d2_9e }, { text: "Is there community?", next: d2_9f }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_9g = { text: "Not really. I keep to myself mostly. I'm not antisocial or anything. I just...don't need a lot of people. I've got a few friends. That's enough. I don't need to be part of some big community scene. Solo works fine for me. Always has.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_9h = { text: "Yeah. I'm pretty independent. Always have been. I don't rely on other people much. I like doing my own thing. Being on my own. It's not lonely—it's just...how I am. Independent. Self-sufficient. Works for me.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_8d = { text: "I don't seek it out much. Community's there if I want it, but I don't really pursue it. I'm more of a solo person. I've got a few friends, but I'm not trying to be part of some big scene. Just...do my own thing. Live my life. Community's fine, but it's not essential for me.", speaker: "D.", choices: [{ text: "Do you prefer solitude?", next: d2_9g }, { text: "Lone wolf type?", next: d2_9h }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_7b = { text: "There's some queer folks around. Not a huge community, but it's there. Scattered across town. Some bars, some events, some spaces. It's small compared to bigger cities, but it exists. People are here. Living their lives. Being queer. It's just...quieter. More low-key. Which suits me fine.", speaker: "D.", choices: [{ text: "What's the community like?", next: d2_8c }, { text: "Do you engage with it?", next: d2_8d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_6a = { text: "Living in Knoxville is just normal for me.", speaker: "D.", choices: [{ text: "Does location matter?", next: d2_7a }, { text: "Are there other queer people?", next: d2_7b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_9i = { text: "Work, home, repeat basically. That's my routine. Wake up, go to work, come home, chill, sleep. Repeat. Not exciting, but it's stable. Predictable. I like that. Some people need variety. Need adventure. Me? I'm fine with routine. Work, home, repeat. It's simple. It works.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_9j = { text: "Yeah. I like routine. Routine is comforting. Predictable. I know what to expect. No surprises. Some people get bored with routine. Not me. I find it soothing. Grounding. Same thing every day? That's fine. That's good, actually. Routine works for me.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_8e = { text: "Pretty simple. Work, chill, repeat. That's my life. I work during the week. Come home and relax. Maybe hike on the weekends. That's it. Nothing complicated. Nothing dramatic. Just...simple. Work, chill, repeat. And that's fine. That's all I need.", speaker: "D.", choices: [{ text: "What do you do?", next: d2_9i }, { text: "You like simple?", next: d2_9j }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_9k = { text: "Not hugely. I just exist. I'm not super active or anything. Don't have a packed social calendar. Don't join clubs or organizations. I just...exist. Go to work, come home, live my life quietly. And that suits me. I don't need to be constantly doing things. Just existing is enough.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_9l = { text: "Yeah. Quiet life is good. No drama. No chaos. No constant stimulation. Just...quiet. Peaceful. I like it that way. Some people need excitement, need noise, need things happening all the time. Not me. Quiet suits me. Always has. Quiet life is a good life.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_8f = { text: "I keep things pretty low-key. Don't make waves. Don't draw attention. Just live quietly. Do my thing. Stay out of drama. Low-key is how I operate. In life, in presentation, in everything. Just...low-key. It's easier that way. Less complicated.", speaker: "D.", choices: [{ text: "Does that suit you?", next: d2_9k }, { text: "You like quiet?", next: d2_9l }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_7c = { text: "My life's pretty chill. No stress. No drama. Just...chill. Work, home, maybe hike on the weekend. That's it. Nothing intense. Nothing complicated. Some people have these busy, hectic lives. Not me. Mine's chill. And I like it that way. Stress-free. Simple. Chill.", speaker: "D.", choices: [{ text: "What's your routine?", next: d2_8e }, { text: "How active are you?", next: d2_8f }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_9m = { text: "Mountains, hiking. Nature stuff. Knoxville's got good access to the mountains. The Smokies aren't far. So I hike when I can. Get out into nature. It's peaceful. Quiet. Just me and the trees. No people, no noise. Just nature. That's my favorite thing to do. Mountains and hiking.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_9n = { text: "Yeah. I like being outside. Nature person, definitely. I'm happiest when I'm outdoors. Hiking, camping, just being in the woods. There's something about nature that's calming. Grounding. No screens, no people, no noise. Just...nature. Trees, mountains, fresh air. That's where I feel best. Outside.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_8g = { text: "I like the outdoors. Mountains. That's my main thing outside of work. Getting out into the mountains, hiking the trails, being in nature. Knoxville's good for that. Easy access to wilderness. I try to get out there when I can. Weekends mostly. Just me and the mountains. That's my thing.", speaker: "D.", choices: [{ text: "What do you do there?", next: d2_9m }, { text: "Nature person?", next: d2_9n }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_9o = { text: "I mean, I work. That's about it. I've got a job. It pays the bills. Nothing fancy. Nothing exciting. Just...work. Go in, do the job, go home. That's my weekday. Work's not my whole life, but it's what I do. Gotta pay the bills somehow. So yeah, I work.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_9p = { text: "Yeah. Pretty straightforward. My life's not complicated. Work, home, outdoors sometimes. That's it. No drama, no chaos, no complexity. Just...straightforward. Simple. And I like it that way. Complicated lives create complicated problems. Straightforward is better. Easier. Less stress.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_8h = { text: "I work, I live. Pretty simple. That's the whole thing, really. I work to pay bills. I live because...that's what you do. It's not complicated. Not dramatic. Just work and live. Simple formula. Works fine for me. Don't need more than that.", speaker: "D.", choices: [{ text: "What do you do for work?", next: d2_9o }, { text: "Simple life?", next: d2_9p }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_7d = { text: "I like the outdoors, mostly. That's my main hobby, if you want to call it that. Hiking, being in the mountains, camping sometimes. Nature stuff. That's what I do when I'm not working. Get outside. Get away from people. Just...outdoors. It's peaceful. That's my thing.", speaker: "D.", choices: [{ text: "Tell me about that.", next: d2_8g }, { text: "What else do you do?", next: d2_8h }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_6b = { text: "Life here is pretty straightforward. No complexity. No drama. I work, I come home, I do my thing. Maybe hike on the weekends. That's it. Knoxville's a pretty straightforward place to live. Affordable. Accessible. Good access to nature. Life's simple here. And simple suits me.", speaker: "D.", choices: [{ text: "What's your daily life like?", next: d2_7c }, { text: "What do you like to do?", next: d2_7d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_5a = { text: "Knoxville is just home. It's where I'm from. Where I live. Where my life is. Nothing more complicated than that. It's not the most exciting place. Not the most progressive. But it's home. It's familiar. And familiar is comfortable. So yeah, Knoxville's just home.", speaker: "D.", choices: [{ text: "Tell me about living here.", next: d2_6a }, { text: "What's life like?", next: d2_6b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_4a = { text: "I'm from Knoxville. Born and raised. Never lived anywhere else. This is home. Always has been. The mountains, the vibe, the people—it's all I know. And that's fine. I'm not looking to leave. Knoxville works for me. It's home.", speaker: "D.", choices: [{ text: "What's that like?", next: d2_5a }, { text: "How is it?", next: d2_5a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_3a = { text: "Just living here, you know. Nothing special about it. I live in Knoxville. I work here. My life is here. That's all there is to it. Not a big story. Just...living here. It's where I am. Where I've always been.", speaker: "D.", choices: [{ text: "Tell me about Knoxville.", next: d2_4a }, { text: "What's it like?", next: d2_4a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d2_2a = { text: "I live in Knoxville. Born and raised here. Never left. It's home, you know? The mountains, the vibe, the familiarity. This is where my life is. Where I work, where I live. Knoxville. Just...home.", speaker: "D.", choices: [{ text: "How's that?", next: d2_3a }, { text: "Cool.", next: d2_3a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };

// Branch 3: 8 choices
const d3_9a = { text: "Yeah. Just living. That's my whole approach to life, really. Just...live. Wake up, do what needs doing, go to bed. Repeat. No grand plan. No deep philosophy. Just living. Works fine for me. Keeps things simple. Keeps things manageable. Just living.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_9b = { text: "Pretty much. Day by day. I don't plan too far ahead. Don't think too hard about the big picture. Just take each day as it comes. Do what needs doing that day. Then move on to the next. Day by day. Simple. Straightforward. Works for me.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_8a = { text: "I just kind of exist honestly. Don't have a big philosophy about life. Don't have grand goals or plans. I just...exist. Wake up, live, go to sleep. And that's fine. That's enough. Some people need more—need meaning, need purpose. Me? I'm good just existing. Simple life. Quiet life. That works.", speaker: "D.", choices: [{ text: "Does that work for you?", next: d3_9a }, { text: "No big philosophy?", next: d3_9b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_9c = { text: "Not really. I just am. Some people spend a lot of time thinking about identity—who they are, what it means, how to express it. Not me. I just am what I am. Don't need to analyze it or define it. Just...am. And that's fine. Simple. Easy. No stress.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_9d = { text: "Yeah. Simple is better. Complexity just creates problems. Overthinking just creates stress. Better to keep things simple. Do what feels right. Don't worry about the rest. Simple life, simple approach. Less stress, more peace. Works for me.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_8b = { text: "I don't overthink things. Overthinking just complicates life. Makes everything harder than it needs to be. Better to just...do. Act. Live. Don't analyze everything to death. Just go with what feels right. Keeps life simple. Keeps stress low. Overthinking's not for me.", speaker: "D.", choices: [{ text: "Do you think about identity much?", next: d3_9c }, { text: "Keep it simple?", next: d3_9d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_7a = { text: "I'm pretty chill about everything. Life, gender, identity, all of it. Don't stress about things I can't control. Don't worry about things that don't matter. Just...chill. Take things as they come. Go with the flow. Stress doesn't help anything. Better to just be chill. Works out fine.", speaker: "D.", choices: [{ text: "How do you approach life?", next: d3_8a }, { text: "No stress?", next: d3_8b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_9e = { text: "Whatever feels right that day. I wake up, check in with myself—what feels right today? What do I need? What am I drawn to? And I follow that. Don't plan it out. Don't overthink it. Just...whatever feels right. Intuitive. Simple. Natural. That's how I operate.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_9f = { text: "Yeah. I go with the flow. Life's easier that way. Fighting the current just makes things harder. Better to just...flow. See where things go. Adapt. Adjust. Go with it. Less resistance, less stress. Just flowing through life. Works fine.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_8c = { text: "I just do what feels natural. Don't force things. Don't perform. Don't try to be something I'm not. Just...do what comes naturally. What feels easy. What feels right. Natural is better than forced. Always. So I just go with what's natural.", speaker: "D.", choices: [{ text: "What does that mean?", next: d3_9e }, { text: "Intuitive living?", next: d3_9f }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_9g = { text: "Not particularly. I just live. Some people need big goals to feel like their life has meaning. Not me. I'm fine just living. Working, hiking, hanging out. That's enough. Don't need some grand purpose. Just...living is fine. Good enough for me.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_9h = { text: "Yeah. Why complicate it? Life's complicated enough without making it more complicated. Better to keep things simple. Live simply. Want simply. Be simply. Complication just creates stress. Simplicity creates peace. I choose peace. Simple as that.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_8d = { text: "I don't have big goals honestly. No five-year plan. No grand ambitions. Just...living. Working. Existing. That's enough for me. Some people need more—need to be striving, achieving, building. Me? I'm content. Just living is goal enough. Simple. Peaceful. Good.", speaker: "D.", choices: [{ text: "Does that bother you?", next: d3_9g }, { text: "Content with now?", next: d3_9h }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_7b = { text: "I just take things as they come. No planning. No strategizing. Just...respond to what's in front of me. Deal with it. Move on. Life unfolds. I adapt. Simple. Flexible. Easy. Planning just creates expectations. Expectations create disappointment. Better to just...take things as they come.", speaker: "D.", choices: [{ text: "No planning?", next: d3_8c }, { text: "Do you have ambitions?", next: d3_8d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_6a = { text: "I'm pretty laid-back about life. Don't stress about things. Don't worry about the future. Don't dwell on the past. Just...exist in the present. Take things as they come. Laid-back is how I operate. In everything. Life's easier when you're laid-back. Less stress, less worry, more peace.", speaker: "D.", choices: [{ text: "How so?", next: d3_7a }, { text: "What's your approach?", next: d3_7b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_9i = { text: "They're fine. I don't stress about them. Labels exist. Some people find them useful. That's cool. Me? I don't think about them much. They're just...there. Tools if you need them. But I don't need them. So I don't stress about them. They're fine. Just not for me.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_9j = { text: "Yeah. I just live my life. Don't worry about what to call myself. Don't worry about fitting into categories. Just...live. Be. Exist. That's enough. Labels aren't necessary for that. I can just live without them. And that's what I do. Simple.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_8e = { text: "I don't think about labels much. They're not important to me. Some people need labels to understand themselves. To explain themselves. Good for them. Me? I don't need that. I know who I am without needing to name it. Labels are optional. And I opt out.", speaker: "D.", choices: [{ text: "Do they matter to you?", next: d3_9i }, { text: "You prefer no labels?", next: d3_9j }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_9k = { text: "Not really. Too limiting. Labels try to fit you into boxes. And I don't fit in boxes. Never have. So why use labels? They just create restrictions. Expectations. Limitations. Better to just...not. Be unlabeled. Undefined. Free. That works better for me.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_9l = { text: "Yeah. I'd rather just be. Just exist without needing to define it. Explanation isn't necessary. Labels aren't necessary. I can just...be. Whatever I am, that's what I am. Don't need to name it. Don't need to explain it. Just be. That freedom—that's valuable to me.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_8f = { text: "I don't use many labels for myself. Never saw the point. I know who I am. I don't need labels to tell me. And I don't need labels to explain myself to others. I can just...be. And people can figure it out or not. Their understanding isn't my responsibility. So I skip the labels.", speaker: "D.", choices: [{ text: "Do you like labels?", next: d3_9k }, { text: "Freedom in that?", next: d3_9l }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_7c = { text: "Identity's not a big thing for me. Some people make identity their whole focus. Their whole life revolves around it. Not me. Identity's just...background. I am who I am. It doesn't need to be analyzed or performed or explained. It just is. And that's enough. No need to make it a big thing.", speaker: "D.", choices: [{ text: "Why not?", next: d3_8e }, { text: "How do you see yourself?", next: d3_8f }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_9m = { text: "I just wear what's comfortable. Jeans, t-shirts, flannels. Work boots. Practical stuff. Nothing fancy, nothing high-maintenance. Just...comfortable. If it feels good, I wear it. If it doesn't, I don't. Comfort is my only criteria. Simple as that.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_9n = { text: "Yeah. Function over form. I don't care what clothes look like. I care if they work. If they're comfortable. If they're practical. Can I move in them? Can I work in them? Can I hike in them? That's what matters. Function. Not fashion. Function over form, always.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_8g = { text: "Practical clothes. Comfortable. Stuff I can work in, move in, live in. Jeans, flannels, boots. Nothing complicated. Nothing that requires special care. Just practical, comfortable clothes. That's my style. If you can call it a style. More like...functional clothing choices.", speaker: "D.", choices: [{ text: "What do you wear?", next: d3_9m }, { text: "Comfort first?", next: d3_9n }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_9o = { text: "Sometimes. When I want to. Some days I feel more masc, so I lean into that. Other days, not so much. It's not consistent. It changes. And that's fine. I present masc when it feels right. When it doesn't, I don't. Simple as that. Sometimes.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_9p = { text: "Yeah. It shifts. Day to day, mood to mood. Sometimes more masc, sometimes less. It's fluid. Not fixed. And I'm fine with that. Don't need it to be the same all the time. Shifting is fine. Natural, even. It shifts. That's just how it is.", speaker: "D.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_8h = { text: "I present however feels right. Don't overthink it. Don't plan it. Just wake up and see what feels right that day. Sometimes that's more masc, sometimes not. Just...whatever feels right. Intuitive. Natural. I follow my gut. Present however feels right in the moment.", speaker: "D.", choices: [{ text: "Do you present masc?", next: d3_9o }, { text: "Does it change?", next: d3_9p }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_7d = { text: "I don't think about my presentation much. Some people plan their whole look. Not me. I just...exist. Wear what's comfortable. Move how I move. Don't think about it. Presentation's not something I analyze or strategize. Just...don't think about it. Works fine that way.", speaker: "D.", choices: [{ text: "What's your style?", next: d3_8g }, { text: "How do you present?", next: d3_8h }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_6b = { text: "I'm pretty go-with-the-flow. About everything, really. Identity, presentation, life. I don't fight things. Don't force things. Just...go with the flow. See where things take me. Adapt as needed. It's easier that way. Less stressful. Go-with-the-flow is my whole approach.", speaker: "D.", choices: [{ text: "About identity?", next: d3_7c }, { text: "About presentation?", next: d3_7d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_5a = { text: "I don't stress about things. Life, identity, presentation, work—none of it. Stress doesn't help. It just makes things harder. So I don't stress. I just...exist. Do what needs doing. Let the rest work itself out. No stress. Easier that way. Better that way.", speaker: "D.", choices: [{ text: "Like what?", next: d3_6a }, { text: "Tell me more.", next: d3_6b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_4a = { text: "Pretty chill about life. Don't overthink things. Don't stress. Don't worry. Just...chill. Take things as they come. Go with the flow. That's my approach to life. Chill. Always has been. Works fine for me. No complaints.", speaker: "D.", choices: [{ text: "How so?", next: d3_5a }, { text: "What does that mean?", next: d3_5a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_3a = { text: "I'm laid-back. About pretty much everything. Life, identity, gender, work—all of it. I don't get worked up. Don't stress. Don't overthink. Just...laid-back. That's my default mode. Always has been. Laid-back is just how I am.", speaker: "D.", choices: [{ text: "About what?", next: d3_4a }, { text: "Tell me.", next: d3_4a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const d3_2a = { text: "Just living. That's my whole thing, really. No big philosophy. No grand plan. Just...living. Day by day. Doing what needs doing. Being who I am. Just living. Simple as that. Works for me.", speaker: "D.", choices: [{ text: "How do you approach life?", next: d3_3a }, { text: "What's your philosophy?", next: d3_3a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };

export const dDialogue = {
  text: "Hey. I'm D. I'm pretty masc presenting, I guess? I don't really think about it that much. Just kind of do my thing here in Knoxville.",
  speaker: "D.",
  choices: [
    { text: "Masc presenting but fluid?", next: d1_2a },
    { text: "What's it like living in Knoxville?", next: d2_2a },
    { text: "You seem pretty laid-back.", next: d3_2a },
    { text: getRandomExitLine(), next: exitNode }
  ]
};
