import { getRandomExitLine, getRandomRestartLine, createExitNode, createRestartMarker } from './dialogueHelpers';

const exitNode = createExitNode();
const restartMarker = createRestartMarker();

// Branch 1: Root→2→3→4→5→6→7→8→9(terminal) = 8 choices
const f1_9a = { text: "Some people get it—usually queer folks who understand gender is more complicated than the binary. Others get confused and don't know what box to put me in, and I'm fine with that.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_9b = { text: "Absolutely—I get to be myself without apology, trans and butch all at once. Realizing I could be both changed everything.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_8a = { text: "Yeah, totally intentional—I'm choosing masculinity because it feels right and it's how I want to move through the world. Being trans and being butch are both deliberate choices about how to embody my gender.", speaker: "F.", choices: [{ text: "How do people react?", next: f1_9a }, { text: "Does that feel freeing?", next: f1_9b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_9c = { text: "The assumption that trans women must be hyper-feminine—that's the hardest expectation because it comes from everywhere. There's this idea that to be a 'real' trans woman you have to want to look like a cis woman, but I never wanted that.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_9d = { text: "I just exist—my existence is the pushback. Showing up as a trans butch woman challenges the expectation that trans women must be feminine.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_8b = { text: "Not really—it's just who I am, being butch is effortless for me. The transition wasn't about becoming someone new but becoming more fully myself.", speaker: "F.", choices: [{ text: "What expectations are hardest?", next: f1_9c }, { text: "How do you push back?", next: f1_9d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_7a = { text: "It's performing masculinity in a queer way—something specifically queer and trans. I'm taking masculinity and making it my own, claiming it on my own terms.", speaker: "F.", choices: [{ text: "That sounds intentional.", next: f1_8a }, { text: "Is that hard to maintain?", next: f1_8b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_9e = { text: "When I realized explaining is exhausting and puts the burden on me to justify my existence. I don't owe anyone an explanation—I can just be.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_9f = { text: "Sometimes, but I'd rather be authentic than comfortable. The alternative—hiding, performing, pretending—is worse, so I choose authenticity even when it's lonely.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_8c = { text: "It took a while to get here—to this place where I can just exist without needing to explain or justify. I had to unlearn the idea that I owed people explanations and build confidence in my identity.", speaker: "F.", choices: [{ text: "When did that shift?", next: f1_9e }, { text: "Does it feel isolating?", next: f1_9f }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_9g = { text: "It's scattered but strong—mostly in online trans, queer, and butch spaces. We're not huge, but we exist and find each other across the country and the world.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_9h = { text: "Essential—knowing I'm not alone makes all the difference. That community validates my existence and reminds me this is real.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_8d = { text: "Definitely—there's a whole community of us, trans women who are masculine. That community has been lifesaving for me, showing me I'm not alone in this.", speaker: "F.", choices: [{ text: "What does that look like?", next: f1_9g }, { text: "How important is that?", next: f1_9h }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_7b = { text: "I just exist as myself—I show up in the world as a trans butch woman and let that speak for itself. Being myself visibly and unapologetically is how I navigate it.", speaker: "F.", choices: [{ text: "That's powerful.", next: f1_8c }, { text: "Do you find community?", next: f1_8d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_6a = { text: "Embracing masculinity had nothing to do with inherent maleness—that's the key thing I had to realize. Masculinity is just a way of being that anyone can claim, so I can be a trans woman and still be masculine.", speaker: "F.", choices: [{ text: "Do aesthetics help?", next: f1_7a }, { text: "How do you navigate that?", next: f1_7b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_9i = { text: "Yeah—the confusion means I'm disrupting the binary and breaking the rules. By existing outside the categories people expect, I'm challenging the system.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_9j = { text: "Sometimes, but it's worth it—the constant confusion and stares can be exhausting. I'd rather be tired from being authentic than comfortable from being someone I'm not.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_8e = { text: "Yeah, the confusion means I'm doing something right—if I fit neatly into existing categories, I wouldn't be challenging anything. The fact that people can't immediately place me means I'm disrupting expectations.", speaker: "F.", choices: [{ text: "That feels radical.", next: f1_9i }, { text: "Does it get tiring?", next: f1_9j }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_9k = { text: "My hips, my chest—subtle but significant changes that helped my body feel more aligned. The interesting thing is, those changes didn't make me less butch.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_9l = { text: "Not really—masculinity isn't about my body, it's about how I present and move through the world. I can have a feminized body and still be masculine in presentation.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_8f = { text: "They helped align my body with how I see myself—hormones gave me physical changes that made me feel more at home. Those changes didn't conflict with my butchness because I could have a more feminine body and still present masculine.", speaker: "F.", choices: [{ text: "What changed most?", next: f1_9k }, { text: "Did you worry about masculinity?", next: f1_9l }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_7c = { text: "A lot of people don't get it, but that ambiguity is intentional—I'm not trying to be easily readable. I'm existing in the space between categories, and for me that's liberating.", speaker: "F.", choices: [{ text: "You embrace confusion?", next: f1_8e }, { text: "How did hormones change things?", next: f1_8f }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_9m = { text: "Exactly—there's instant connection when you find your people. That immediate recognition where we don't have to explain ourselves is rare and precious.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_9n = { text: "More than you'd think—queer people have radar. It happens often enough to sustain me and remind me that community exists, even if it's scattered.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_8g = { text: "When I meet other queer people and we just get each other—when I spot another trans person or butch who understands existing outside the binary. That recognition is beautiful, and visibility feels good because it creates connection instead of vulnerability.", speaker: "F.", choices: [{ text: "Like finding your people?", next: f1_9m }, { text: "Does that happen often?", next: f1_9n }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_9o = { text: "I've gotten good at ignoring it—the stares, the whispers, the double-takes. I block it out and keep my head up because it's a survival mechanism.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_9p = { text: "Where I live, yeah, but I'm always aware—even in New York I'm calculating if this space is safe. There's always a background hum of vigilance, which is the reality of being visibly trans.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_8h = { text: "When I'm just trying to exist and people stare—when visibility isn't about connection but about scrutiny. That's when it doesn't feel good, when I become a spectacle instead of a person.", speaker: "F.", choices: [{ text: "How do you handle that?", next: f1_9o }, { text: "Do you feel safe?", next: f1_9p }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_7d = { text: "Sometimes being trans and visible is complicated—I want other trans people to see me and know they're not alone. But visibility also comes with risk and scrutiny, so it's this double-edged thing I navigate constantly.", speaker: "F.", choices: [{ text: "When is visibility nice?", next: f1_8g }, { text: "When is it not nice?", next: f1_8h }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_6b = { text: "Well, hormones helped—they changed my body in ways that made me feel more comfortable and aligned with myself. But they didn't change my butchness, because I could have a more feminine body and still be masculine in presentation.", speaker: "F.", choices: [{ text: "Did your masculinity shift?", next: f1_7c }, { text: "Did it feel freeing?", next: f1_7d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_5a = { text: "That feels really specific—being butch and trans simultaneously. Most people think of trans women as feminine, and they think of butches as people assigned female at birth who stayed that way.", speaker: "F.", choices: [{ text: "Tell me more.", next: f1_6a }, { text: "How does that work?", next: f1_6b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_4a = { text: "Being butch and trans at once—that's the core of it. I'm a trans woman who transitioned to womanhood, and I'm butch, which means I express that womanhood through masculinity.", speaker: "F.", choices: [{ text: "How do you hold both?", next: f1_5a }, { text: "What does that look like?", next: f1_5a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_3a = { text: "Masculinity doesn't equal maleness for me—that's the key insight I had to reach. For a long time I thought masculinity belonged to men, but it's just a set of behaviors and aesthetics anyone can claim.", speaker: "F.", choices: [{ text: "Explain that.", next: f1_4a }, { text: "How did you figure that out?", next: f1_4a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f1_2a = { text: "I'm a trans woman but I'm butch with it—that's how I describe myself. I transitioned because I'm a woman, but I express that womanhood through masculinity.", speaker: "F.", choices: [{ text: "That's interesting.", next: f1_3a }, { text: "Tell me more.", next: f1_3a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };

// Branch 2: 8 choices
const f2_9a = { text: "By being myself unapologetically—I just exist as a trans butch woman and let that speak for itself. By showing up visibly trans and masculine, I'm challenging the expectation that trans women must be feminine.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_9b = { text: "Slowly—more trans women are publicly claiming masculinity and identifying as butch. Every person who comes out as a trans butch makes it easier for the next person.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_8a = { text: "It is, especially from within the trans community. When you reject femininity and say you're also masculine, some people question whether you're really trans.", speaker: "F.", choices: [{ text: "How do you resist?", next: f2_9a }, { text: "Is it changing?", next: f2_9b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_9c = { text: "I wish someone had told me when I was younger that being trans doesn't mean you have to be feminine. That would have saved me years of thinking I had to choose between being trans and being myself.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_9d = { text: "Not formally, but I try to be visible because visibility matters. When younger trans people see it's possible to be trans and butch simultaneously, that opens up possibilities for them.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_8b = { text: "That it's okay—you don't have to fit a mold or perform femininity just because you're a trans woman. You can express your womanhood however feels right to you.", speaker: "F.", choices: [{ text: "That's powerful.", next: f2_9c }, { text: "Do you mentor anyone?", next: f2_9d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_7a = { text: "There's this hyper focus on looking like Hunter Schafer—on being conventionally feminine and passing as cis. If you don't fit that narrow mold, you're seen as doing it wrong.", speaker: "F.", choices: [{ text: "That pressure sounds exhausting.", next: f2_8a }, { text: "What would you tell younger trans women?", next: f2_8b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_9e = { text: "Definitely—and it's beautiful seeing more trans women publicly claim butchness. It's expanding what butchness means, making space for all of us.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_9f = { text: "It makes it richer and more diverse. The butch community gets better when it includes trans women because diversity strengthens us and opens up new possibilities.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_8c = { text: "That's the goal—we're challenging who gets to be butch. We're expanding the definition beyond people assigned female at birth and making butchness more inclusive.", speaker: "F.", choices: [{ text: "Do you see more trans women claiming it?", next: f2_9e }, { text: "How does that change community?", next: f2_9f }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_9g = { text: "I am hopeful—change is slow but happening. More people are talking about trans butches now than five years ago, and younger trans people especially are more open to the idea.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_9h = { text: "Seeing younger people feel free to experiment without fitting one narrow mold. They're exploring masculinity, femininity, everything in between, and creating their own versions of what it means to be trans.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_8d = { text: "I think it's going to keep opening up—the definitions of butchness and trans womanhood are both expanding. Those expansions create space for people like me, and I think we'll see more trans butch women claiming this identity publicly.", speaker: "F.", choices: [{ text: "That sounds hopeful.", next: f2_9g }, { text: "What gives you that hope?", next: f2_9h }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_7b = { text: "Butchness is evolving and expanding who gets to claim it. It's becoming more inclusive, and I'm part of that evolution.", speaker: "F.", choices: [{ text: "That feels inclusive.", next: f2_8c }, { text: "Where do you see it going?", next: f2_8d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_6a = { text: "I want trans people to realize they have options—that there's more than one way to be trans. You don't have to fit the narrow narrative of what a trans woman should look like.", speaker: "F.", choices: [{ text: "More than one way to do womanhood.", next: f2_7a }, { text: "You're broadening the blueprint.", next: f2_7b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_9i = { text: "Yeah, butchness challenges expectations—it disrupts people's assumptions about what trans women should be. When you're butch and trans, you're breaking two sets of rules at once.",  speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_9j = { text: "Not really—there's always been variety in how people express gender. Historically, trans people have always been diverse in presentation; the myth of one correct way is relatively new.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_8e = { text: "Some people embrace it, but others push back hard, especially within the trans community. There can be pressure to conform to certain narratives about what it means to be a trans woman.", speaker: "F.", choices: [{ text: "Is that surprising?", next: f2_9i }, { text: "Were people always accepting?", next: f2_9j }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_9k = { text: "Younger trans folks seem more open to the idea that gender can be complex and multifaceted. They're less invested in rigid narratives, which creates more space for people like me.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_9l = { text: "Yeah, the narrative is slowly shifting toward more inclusive understandings of trans identity. We're moving away from the idea that there's one right way to be trans.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_8f = { text: "I think younger generations get it more because they've grown up with more diverse representations of trans people. They're less surprised by someone like me.", speaker: "F.", choices: [{ text: "They're more accepting?", next: f2_9k }, { text: "Things are changing?", next: f2_9l }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_7c = { text: "It varies widely—some people embrace it immediately. Others question whether I'm 'really trans' if I'm not feminine.", speaker: "F.", choices: [{ text: "How do people usually react?", next: f2_8e }, { text: "Does age matter?", next: f2_8f }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_9m = { text: "Just by existing and being visible—by showing up in the world as a trans butch woman. My presence itself is a statement that this is possible, that you can be both things at once.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_9n = { text: "Yeah, I talk about it when the opportunity arises in online spaces and community settings. The more we talk about it, the more normal it becomes.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_8g = { text: "I try to be visible and show it's possible to be trans and butch simultaneously. When people see me, they know this identity exists.", speaker: "F.", choices: [{ text: "Just by being yourself?", next: f2_9m }, { text: "Do you advocate actively?", next: f2_9n }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_9o = { text: "Definitely—representation changes everything. When you see someone like yourself reflected in the world, it validates your existence and shows you that what you're feeling is real.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_9p = { text: "Yeah, it gives people permission to explore their own identities without fear. Seeing someone else do it first makes it feel less scary and less impossible.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_8h = { text: "I hope so—that's why visibility matters to me. If even one person sees me and realizes they don't have to choose between being trans and being masculine, it's worth it.", speaker: "F.", choices: [{ text: "Does seeing others help?", next: f2_9o }, { text: "Is representation important?", next: f2_9p }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_7d = { text: "I want to expand what people think is possible and show that being trans isn't a monolithic experience. There are so many ways to be trans, and masculinity is one of them.", speaker: "F.", choices: [{ text: "How do you do that?", next: f2_8g }, { text: "Do you think it's working?", next: f2_8h }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_6b = { text: "I want trans people to realize they have options beyond the narrow narrative we're often given. You don't have to perform femininity to be a valid trans woman.", speaker: "F.", choices: [{ text: "How do others respond?", next: f2_7c }, { text: "What's your role in that?", next: f2_7d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_5a = { text: "What do I want younger people to take from my identity? That there's no one right way to be trans—you can be a trans woman and still be masculine, still be butch.", speaker: "F.", choices: [{ text: "Tell me more.", next: f2_6a }, { text: "What's important to you?", next: f2_6b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_4a = { text: "Representation and visibility matter because they show people what's possible. When you see someone like yourself existing in the world, it gives you permission to exist that way too.", speaker: "F.", choices: [{ text: "What do you want to show?", next: f2_5a }, { text: "Who are you representing?", next: f2_5a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_3a = { text: "I want to expand possibilities for what being trans can look like. The narrative has been so narrow for so long, and I want to show there are other ways to exist.", speaker: "F.", choices: [{ text: "How so?", next: f2_4a }, { text: "What does that mean?", next: f2_4a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f2_2a = { text: "Younger people need to see options beyond the standard trans narrative. They need to know that being trans doesn't mean you have to look or act a certain way.", speaker: "F.", choices: [{ text: "What options?", next: f2_3a }, { text: "Tell me more.", next: f2_3a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };

// Branch 3: 8 choices
const f3_9a = { text: "It just describes how I show up—language is a tool for communication. The words help me communicate who I am, but the lived experience is what matters.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_9b = { text: "Yeah—trans and butch, both at once. Those two identities coexist in me simultaneously, not sequentially.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_8a = { text: "They're just words—the lived experience matters more. I use labels because they're useful for communication, but I don't let them define me completely.", speaker: "F.", choices: [{ text: "Language is a tool?", next: f3_9a }, { text: "You hold multiple identities?", next: f3_9b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_9c = { text: "Not really—they're just different lenses on the same reality. One describes my history and journey, the other describes my presentation and aesthetic.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_9d = { text: "They describe different aspects of me—butch describes how I present with masculinity and energy. Trans describes my history, that I transitioned away from what I was assigned at birth.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_8b = { text: "Butch is how I present, trans is my history. How I show up in the world is butch; where I came from is trans.", speaker: "F.", choices: [{ text: "Do they conflict?", next: f3_9c }, { text: "How do they relate?", next: f3_9d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_7a = { text: "It's less a category, more a way of being—butchness isn't something I am, it's something I do. It's how I move through the world and take up space.", speaker: "F.", choices: [{ text: "How do you think about labels?", next: f3_8a }, { text: "What does butch mean to you?", next: f3_8b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_9e = { text: "Yeah, presentation is how you move through space—it's your physical presence in the world. It's how you take up room and interact with your environment.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_9f = { text: "Exactly—it's energy, style, attitude, all together. Clothes are part of it, but so is how you walk, hold yourself, and speak.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_8c = { text: "It's about how I carry myself and my energy—the vibe I project into the world. Butchness isn't just what I wear, it's how I exist in my body.", speaker: "F.", choices: [{ text: "It's embodied?", next: f3_9e }, { text: "More than just clothes?", next: f3_9f }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_9g = { text: "Confidence and taking up space without apology—not shrinking myself to make others comfortable. Existing fully and unapologetically in my body.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_9h = { text: "Yeah, refusing to shrink myself or make myself smaller for other people's comfort. Presence means claiming space, being visible, not hiding.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_8d = { text: "How I take up space and exist in the world—it's about presence, visibility, refusing to hide. Butchness is claiming space unapologetically.", speaker: "F.", choices: [{ text: "What does that mean?", next: f3_9g }, { text: "Is it about presence?", next: f3_9h }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_7b = { text: "Butchness is a language—a way of communicating who I am without words. It's how I tell the world about my identity and relationship to gender.", speaker: "F.", choices: [{ text: "What are you communicating?", next: f3_8c }, { text: "What's the message?", next: f3_8d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_6a = { text: "You make butchness sound less like a category—and yeah, that's intentional. I think of it as something more fluid and active than a rigid identity box.", speaker: "F.", choices: [{ text: "How do you see it?", next: f3_7a }, { text: "What is it then?", next: f3_7b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_9i = { text: "Clothes, haircut, the way I move through space—it's all intentional. My short hair, masculine clothing, and body language communicate who I am.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_9j = { text: "Yeah, all of it together creates the vibe—no single element does the work alone. It's the combination of presentation, energy, and attitude that makes butchness.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_8e = { text: "All of it—style, posture, energy, how I carry myself. Presentation is the totality of how you show up in the world.", speaker: "F.", choices: [{ text: "Give me examples?", next: f3_9i }, { text: "It's holistic?", next: f3_9j }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_9k = { text: "Definitely—it makes me feel like myself in a way nothing else does. When my presentation matches my internal sense of self, everything clicks into place.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_9l = { text: "Yeah, looking right helps me feel right—there's alignment between how I see myself internally and how I present externally. When those match, I feel whole.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_8f = { text: "For me, yeah—how I look affects how I feel in profound ways. Presentation isn't superficial, it's deeply connected to my sense of self.", speaker: "F.", choices: [{ text: "That's important to you?", next: f3_9k }, { text: "Inside and outside match?", next: f3_9l }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_7c = { text: "Presentation matters because it's how you show who you are to the world. For me, that alignment between inside and outside is crucial.", speaker: "F.", choices: [{ text: "What counts as presentation?", next: f3_8e }, { text: "Does it matter to you?", next: f3_8f }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_9m = { text: "Exactly—I'm living proof it's possible to be both trans and butch. Just by existing, I demonstrate that this identity is real and valid.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_9n = { text: "Yeah, by being myself I challenge norms about what trans women should be. My existence disrupts expectations, and that's activism whether I'm trying to be political or not.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_8g = { text: "By showing it's possible and by being visible. When people see me, they learn that trans women can be masculine.", speaker: "F.", choices: [{ text: "You're an example?", next: f3_9m }, { text: "Visibility as activism?", next: f3_9n }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_9o = { text: "Yeah, it makes what I'm doing feel meaningful—knowing my visibility might help someone else. My existence could make life easier for the next trans butch person.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_9p = { text: "Definitely—it's why I stay visible even when it's hard. The possibility that I might help someone else navigate their identity makes the difficulty worth it.", speaker: "F.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_8h = { text: "I hope so—that's the dream anyway. If my visibility helps even one person feel less alone or confused about their identity, it's worth it.", speaker: "F.", choices: [{ text: "That's important to you?", next: f3_9o }, { text: "Does that motivate you?", next: f3_9p }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_7d = { text: "I want to expand what people think is possible—show that gender categories are more flexible than we're taught. Trans women can be masculine, and butchness can include trans people.", speaker: "F.", choices: [{ text: "How do you do that?", next: f3_8g }, { text: "Do you think it helps others?", next: f3_8h }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_6b = { text: "You make butchness sound expansive—and it is. Butchness is a broad way of being that can include many different kinds of people, including trans women like me.", speaker: "F.", choices: [{ text: "How do you show that?", next: f3_7c }, { text: "What's your goal?", next: f3_7d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_5a = { text: "Butchness sounds less like a category to me because I think categories can be limiting. I prefer to think of it as a practice, a way of being in the world.", speaker: "F.", choices: [{ text: "Explain that more.", next: f3_6a }, { text: "Tell me what you mean.", next: f3_6b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_4a = { text: "It's more like a language—a system of communication about who you are. Butchness communicates something about your relationship to gender and masculinity.", speaker: "F.", choices: [{ text: "A language of what?", next: f3_5a }, { text: "How so?", next: f3_5a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_3a = { text: "Butchness is complicated—it's not just one thing. It's a combination of presentation, attitude, energy, and history.", speaker: "F.", choices: [{ text: "In what way?", next: f3_4a }, { text: "Tell me more.", next: f3_4a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const f3_2a = { text: "Labels are interesting—I use them because they're useful tools for communication. But I try not to let labels define me completely or limit what I can be.", speaker: "F.", choices: [{ text: "How do you use them?", next: f3_3a }, { text: "What do they mean to you?", next: f3_3a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };

export const fDialogue = {
  text: "So, I'm technically a trans woman, but I'm butch with it because I don't personally see masculinity and butchness to be something inherent to like cis masculinity, and I never saw myself as a boy for my whole life.",
  speaker: "F.",
  choices: [
    { text: "That feels really specific in a way I don't hear often.", next: f1_2a },
    { text: "What do you want younger people to take from your identity?", next: f2_2a },
    { text: "You make butchness sound less like a category and more like a language.", next: f3_2a },
    { text: getRandomExitLine(), next: exitNode }
  ]
};
