import { getRandomExitLine, getRandomRestartLine, createExitNode, createRestartMarker } from './dialogueHelpers';

const exitNode = createExitNode();
const restartMarker = createRestartMarker();

// Branch 1: 8 choices
const j1_9a = { text: "Both. Inside and outside pressure. Externally, people have this very specific idea of what Black masculinity should look like—aggressive, hypermasculine, dangerous. And internally, I've absorbed some of that too. I catch myself policing my own behavior, wondering if I'm being 'too much' or 'not enough.' It's exhausting navigating both at once.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_9b = { text: "Definitely. Labels can trap you. People want you to fit neatly into categories—butch, stud, masc, whatever. But those labels come with expectations. And when you're Black, those expectations get even more rigid. Like there's one correct way to be a Black masc person. But that's not me. I don't fit the mold, and I'm okay with that even when it's hard.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_8a = { text: "Expectations about how Black masc folks should be. There's this stereotype that we're supposed to be hard, aggressive, emotionally closed off. That we're dangerous or threatening. And those stereotypes come from both outside the Black community and within it. People project that onto me before they even know me. They see my skin color and my presentation and make assumptions.", speaker: "J.", choices: [{ text: "Internal or external?", next: j1_9a }, { text: "Does that limit you?", next: j1_9b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_9c = { text: "I just show up as myself. I refuse to perform toughness or aggression if that's not what I'm feeling. I refuse to make myself smaller or softer to be more palatable either. I just am who I am. Some days that's easier than others. Some days I have the energy to resist expectations. Other days I'm just trying to survive.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_9d = { text: "Yeah. Authenticity over everything. I spent too long trying to fit into boxes that weren't made for me. Trying to be the right kind of Black. The right kind of masc. The right kind of queer. But none of those boxes fit. So I stopped trying. Now I just focus on being authentic, even when that makes people uncomfortable.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_8b = { text: "By not performing for anyone. I used to code-switch constantly. Change how I talked, how I moved, how I presented depending on who I was around. But that was exhausting. Now I just show up as myself. Same person in every space. It's scary sometimes, but it's honest. And I need that honesty to survive.", speaker: "J.", choices: [{ text: "You resist expectations?", next: j1_9c }, { text: "Authentic presentation?", next: j1_9d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_7a = { text: "People have expectations. I don't always fit them. As a Black masc person, people expect me to be aggressive, hypermasculine, dangerous. Or they expect me to perform softness to counteract those stereotypes. But I'm neither. I'm just me. And that confuses people. They don't know what to do with a Black masc person who doesn't fit their preconceived ideas.", speaker: "J.", choices: [{ text: "What expectations?", next: j1_8a }, { text: "How do you navigate that?", next: j1_8b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_9e = { text: "Sometimes. But I stay true to myself. There are days when I'm exhausted by it. When I just want to blend in, to not have to think about how I'm being perceived. But then I remember that shrinking myself doesn't actually keep me safe. And it definitely doesn't make me happy. So I choose authenticity even when it's hard.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_9f = { text: "Yeah. It takes energy. Constant energy. Navigating other people's expectations, managing their discomfort, educating them when they ask invasive questions. Dealing with the microaggressions and the stereotypes. Some days I have that energy. Other days I'm running on empty. But I don't really have the option to stop. This is my life.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_8c = { text: "It's exhausting sometimes. Constantly navigating expectations, constantly being aware of how I'm being perceived. As a Black person, I'm already hypervisible in certain ways. Add being masc and queer to that, and I'm always under scrutiny. People are always watching, always judging. That takes a toll.", speaker: "J.", choices: [{ text: "Does it get to you?", next: j1_9e }, { text: "That sounds draining.", next: j1_9f }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_9g = { text: "Not always. But I try to find them. Community is scattered here in Knoxville. There's not a huge population of Black queer folks, especially Black masc folks. So I find community where I can—online, in other cities, with the few people here who get it. It's not perfect, but it's something.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_9h = { text: "Yeah. Community makes it easier. When you find people who understand your specific experience—who don't need you to explain or justify yourself—that's powerful. That's survival. I need to know I'm not alone in this. That other people are navigating the same shit. Community reminds me I'm not crazy. That the world is what's broken, not me.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_8d = { text: "Finding people who get it helps. People who understand the intersection of being Black and masc and queer. People who don't make me explain why those identities matter or how they shape each other. That understanding is rare, but when I find it, it's like oxygen. It keeps me going.", speaker: "J.", choices: [{ text: "Do you have that?", next: j1_9g }, { text: "Is community important?", next: j1_9h }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_7b = { text: "Labels can be limiting. They create expectations. People hear 'stud' or 'butch' or 'masc' and they think they know who you are. They think they know how you should act, how you should look, who you should be. And when you don't fit that mold—when you're softer or more emotional or different in any way—they get confused or judgmental. Labels can be useful, but they can also trap you.", speaker: "J.", choices: [{ text: "How so?", next: j1_8c }, { text: "Do you find support?", next: j1_8d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_6a = { text: "Being Black and masc presents specific challenges. Stereotypes about Black masculinity are everywhere—aggressive, dangerous, hypersexual. And then add being queer to that mix, and you're navigating multiple layers of prejudice. People see me and make assumptions before I've said a word. That affects everything—where I can go, how safe I feel, how I present myself.", speaker: "J.", choices: [{ text: "Like what?", next: j1_7a }, { text: "Tell me about that.", next: j1_7b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_9i = { text: "Visibility can be dangerous. As a Black person, I'm already hypervisible in certain spaces. Add being visibly queer and masc to that, and I become even more of a target. People stare. People follow me in stores. People cross the street to avoid me. And that's just the everyday stuff. The real danger is violence—verbal, physical, systemic. Being visible means being vulnerable.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_9j = { text: "Yeah. I'm always aware. Always calculating risk. Which spaces are safe? Who's around me? Who's watching? What's the quickest exit? It's exhausting living in that constant state of vigilance. But it's also survival. I don't have the luxury of letting my guard down. Not here in the South. Not as a Black queer person.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_8e = { text: "Safety is always a consideration. I have to think about it constantly. Before I go somewhere, I'm assessing—is this a safe space? Will I be the only Black person? The only visibly queer person? What's the risk? And then I decide whether it's worth it. Whether I have the energy to navigate that space. Whether I can afford to be visible there.", speaker: "J.", choices: [{ text: "How does that affect you?", next: j1_9i }, { text: "Do you stay vigilant?", next: j1_9j }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_9k = { text: "I pick my battles. Choose my spaces. Some spaces I know are safe—queer spaces, Black spaces, places where I have community. Other spaces I avoid because they're not worth the risk. And then there are spaces where I calculate—is this necessary? Do I need to be here? Can I afford the emotional labor of navigating this? I'm constantly making those calculations.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_9l = { text: "Yeah. Strategic visibility. I decide when and where to be visible based on context. In queer spaces, I can relax a bit. In white spaces or straight spaces, I'm more guarded. I might tone down my presentation, code-switch my language, make myself smaller. It's not hiding—it's survival. It's choosing when to fight and when to conserve energy.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_8f = { text: "I navigate spaces carefully. I'm always reading the room, assessing who's there, what the vibe is, whether I'm safe. It's like having a sixth sense for danger. I can feel when a space is hostile. And then I decide—do I leave? Do I stay but make myself smaller? Do I push back? Every space requires a different strategy.", speaker: "J.", choices: [{ text: "How do you decide?", next: j1_9k }, { text: "Calculated risk?", next: j1_9l }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_7c = { text: "Visibility is complex for me. On one hand, I want to be visible. I want to exist loudly, to claim space, to show other Black queer folks that we're here. But visibility also comes with risk. People see me and make assumptions. They perceive me as threatening. They treat me differently. So I'm constantly balancing—how visible can I afford to be in this moment?", speaker: "J.", choices: [{ text: "Why?", next: j1_8e }, { text: "How do you manage that?", next: j1_8f }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_9m = { text: "Yeah. Intersectionality is real. My experience of masculinity is shaped by my Blackness. My experience of Blackness is shaped by my queerness. You can't separate them. They're not discrete parts of me that exist independently. They're woven together. My Black masculinity is different from white masculinity. My queer Blackness is different from straight Blackness. All my identities inform each other.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_9n = { text: "Definitely. They shape each other. Being Black affects how I experience being masc. Being masc affects how I experience being Black. Being queer affects both. They're not additive—like I'm Black plus masc plus queer. They're multiplicative. They create something specific. Black masc queerness is its own thing. You can't understand one without understanding all of them.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_8g = { text: "My Blackness and masculinity are intertwined. I can't do masculinity the way white queer folks do. My Blackness changes it. Black masculinity carries different stereotypes, different dangers, different meanings. And being masc and queer changes how I navigate Blackness. All of these identities are braided together. You pull on one thread and the whole thing shifts.", speaker: "J.", choices: [{ text: "They can't be separated?", next: j1_9m }, { text: "Do they inform each other?", next: j1_9n }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_9o = { text: "Not really. It's who I am. I don't sit around wishing I could just be one thing—just Black or just queer or just masc. That's not how identity works. I'm all of those things all the time. They're inseparable. And honestly, I wouldn't want to separate them even if I could. They make me who I am.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_9p = { text: "Yeah. I'm whole as I am. All my identities together—that's the full picture. That's me. Trying to separate them would be like trying to separate ingredients that have already been baked into a cake. They've transformed into something new together. Something that can't be broken down into parts anymore.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_8h = { text: "I can't separate my identities. They're not discrete categories I can put in different boxes. I'm not Black in one context and masc in another and queer in another. I'm all of those things simultaneously, all the time. They shape each other. They create the specific person that I am. You can't understand my masculinity without understanding my Blackness. You can't understand my Blackness without understanding my queerness.", speaker: "J.", choices: [{ text: "Do you want to?", next: j1_9o }, { text: "They're all you?", next: j1_9p }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_7d = { text: "Race and gender intersect for me. They're not separate experiences. Being a Black masc person is different from being a white masc person. The stereotypes are different. The dangers are different. The way people perceive you is different. My Blackness shapes how people read my gender. My gender shapes how people read my race. They can't be disentangled.", speaker: "J.", choices: [{ text: "How so?", next: j1_8g }, { text: "Can you separate them?", next: j1_8h }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_6b = { text: "Being Black shapes my gender experience. The way I experience being masc is different because I'm Black. Black masculinity carries specific stereotypes—dangerous, aggressive, hypersexual. Those stereotypes shape how people perceive me. They shape how safe I am. They shape what spaces I can navigate. My race isn't separate from my gender. They're intertwined.", speaker: "J.", choices: [{ text: "Tell me about visibility.", next: j1_7c }, { text: "How does race play in?", next: j1_7d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_5a = { text: "Labels and expectations are tricky. People want to categorize you. They want you to fit into neat boxes. But those boxes are often too small, too rigid. Especially for Black masc folks. The labels available don't always fit. And the expectations that come with those labels can be limiting. I navigate that by holding labels loosely. Using them when they're useful, rejecting them when they're not.", speaker: "J.", choices: [{ text: "How so?", next: j1_6a }, { text: "Tell me more.", next: j1_6b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_4a = { text: "Navigating identity is complex. It's not just one thing. I'm Black. I'm masc. I'm queer. All of those identities intersect and shape each other. And navigating them in Knoxville, in the South, as a visibly Black queer person—that adds layers of complexity. Safety, visibility, community, expectations—all of it is interconnected. All of it requires navigation.", speaker: "J.", choices: [{ text: "What makes it complex?", next: j1_5a }, { text: "Explain.", next: j1_5a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_3a = { text: "Being Black and masc has layers. There are stereotypes about Black masculinity—that we're aggressive, dangerous, hypersexual. And then there are expectations within the queer community about what masc should look like. Navigating both of those at once requires constant awareness. Constant code-switching. Constant calculation of risk and visibility.", speaker: "J.", choices: [{ text: "What layers?", next: j1_4a }, { text: "Tell me.", next: j1_4a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j1_2a = { text: "There's a lot to navigate. Being Black and masc and queer in Knoxville—all of that comes with challenges. Stereotypes, expectations, safety concerns, visibility, community. Every day I'm making calculations about how to move through the world. Where it's safe to be myself. Where I need to code-switch. Who I can trust. It's constant work.", speaker: "J.", choices: [{ text: "Like what?", next: j1_3a }, { text: "Tell me more.", next: j1_3a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };

// Branch 2: 8 choices
const j2_9a = { text: "It's complicated in ways that are hard to explain to people who don't live it. I'm always running calculations in my head—is this space safe? Who's watching me? What are the exits? How am I being perceived? It's like having a background program running all the time, constantly assessing threat levels. Some days that calculation is quiet, almost automatic. Other days it's so loud I can barely think about anything else.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_9b = { text: "Hyper-awareness isn't optional—it's how I stay safe. I notice everything. Who's in a room when I walk in. Who looks at me and how. The energy of a space. Whether people are comfortable or tense around me. I track all of it without even thinking about it anymore. It's exhausting, but it's kept me alive. It's kept me from walking into situations that could turn dangerous.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_8a = { text: "In the South, as a Black queer person, safety is never guaranteed. The South has a particular history with Black bodies, with queer bodies. That history is still alive. It shows up in how people look at you, how they treat you, what they assume about you. There's a weight to being visibly Black and visibly queer here. You feel it in your body. You carry it everywhere.", speaker: "J.", choices: [{ text: "How does that feel?", next: j2_9a }, { text: "Do you stay alert?", next: j2_9b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_9c = { text: "I'm strategic. I know which neighborhoods are safer, which bars are welcoming, which coffee shops I can relax in. I know where the queer-friendly spaces are, and I know where I'm likely to get stared at or worse. I plan my routes. I choose my timing. I don't just wander into places without thinking. Every outing requires a mental risk assessment first.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_9d = { text: "Yeah. There are places I just don't go. Rural areas, certain bars, certain parts of town. Places where Confederate flags still fly. Places where I know I'd be the only Black person, the only visibly queer person. Those places aren't worth the risk. I've learned to trust my gut. If a place feels hostile, I leave. I don't push it.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_8b = { text: "I navigate spaces carefully. I'm always assessing—what's the vibe here? Who's around? Am I safe? Before I enter a new space, I'm already looking for exits, reading the energy, deciding whether I can afford to be visible here. It's automatic now. I don't even realize I'm doing it half the time. But it's constant.", speaker: "J.", choices: [{ text: "How do you choose spaces?", next: j2_9c }, { text: "Are there unsafe places?", next: j2_9d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_7a = { text: "Safety is always on my mind because it has to be. I don't have the privilege of moving through the world without thinking about it. As a Black masc person in the South, I'm navigating layers of potential danger—racism, homophobia, transphobia, misogyny. Any one of those could turn a normal day dangerous. So I stay aware. I stay strategic. I protect myself because I have to.", speaker: "J.", choices: [{ text: "Why?", next: j2_8a }, { text: "How do you manage?", next: j2_8b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_9e = { text: "Some folks understand because they live it too—other Black queer folks, other people who navigate multiple marginalized identities. They get it without explanation. But most people don't. Most people don't understand what it's like to constantly calculate risk, to always be aware of your visibility, to never fully relax. They think I'm being paranoid or oversensitive. They don't see the real threats I'm navigating.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_9f = { text: "Yeah, it's isolating. Living with this level of vigilance, with this constant awareness—it sets you apart. People who don't have to think about safety the way I do can't fully understand what my daily life is like. And that creates distance. I can't fully explain it, and they can't fully grasp it. So there's this gap. This loneliness that comes from navigating the world so differently.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_8c = { text: "There's not a lot of folks like me here in Knoxville. Black masc queer people—we're not a huge population here. So finding community, finding people who understand the specific intersection of my identities, is hard. Most of the queer spaces here are predominantly white. Most of the Black spaces here are predominantly straight. I exist in the margins of both.", speaker: "J.", choices: [{ text: "Do people get it?", next: j2_9e }, { text: "Is that lonely?", next: j2_9f }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_9g = { text: "Online mostly. There are Black queer communities online where I can connect with people who get it. And there are some local folks—a small group of us who've found each other. We're scattered, but we exist. We check in on each other, support each other, create little pockets of safety for each other. It's not a big community, but it's real.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_9h = { text: "Yeah, it's essential. Community is how I survive. Knowing I'm not alone in this, that other people are navigating the same shit—that keeps me going. Community is where I can exhale, where I don't have to explain myself, where I can just be. Without it, I don't know if I'd make it. The isolation would be too much.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_8d = { text: "I find community where I can. It's not always easy. Knoxville isn't a huge city, and the Black queer population here is small. So I look online. I travel to other cities when I can. I connect with people through social media, through events, through word of mouth. I build community deliberately because it doesn't just happen organically here.", speaker: "J.", choices: [{ text: "Where do you find it?", next: j2_9g }, { text: "Is it important?", next: j2_9h }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_7b = { text: "Community is scattered here because there aren't a lot of us. Black queer folks in Knoxville—we're spread out. We're not concentrated in one neighborhood or one set of spaces. So finding each other takes effort. It takes intentionality. You have to seek people out, build connections deliberately. It's not like bigger cities where there's a visible, established Black queer scene.", speaker: "J.", choices: [{ text: "Why scattered?", next: j2_8c }, { text: "Do you find people?", next: j2_8d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_6a = { text: "Living here requires constant navigation. Knoxville is a Southern city with all the history and baggage that comes with that. For a Black queer person, that means navigating racism, homophobia, and the particular ways those things intersect in the South. It means being strategic about where you go, who you trust, how visible you are. Every day is a series of calculations about safety and risk.", speaker: "J.", choices: [{ text: "How so?", next: j2_7a }, { text: "What's the community like?", next: j2_7b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_9i = { text: "Yeah, it's scary. Not in a constant panic way, but in a background hum of anxiety way. I know that my visibility makes me vulnerable. I know that some people see me and feel threatened or disgusted or curious in invasive ways. I know that visibility can lead to harassment, to violence, to being targeted. So yeah, it's scary. But I also refuse to make myself invisible to stay safe.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_9j = { text: "Definitely. I'm always aware. Even in spaces that feel relatively safe, I'm tracking who's around me, what's happening, how people are responding to my presence. It's like a background program that never shuts off. I'm aware of exits, aware of who might be a threat, aware of how to de-escalate if needed. That awareness is exhausting, but it's necessary.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_8e = { text: "Visibility puts me at risk because it makes me a target. When you're visibly Black and visibly queer and visibly gender non-conforming, you stand out. People notice you. And some of those people are hostile. Some of them are dangerous. Visibility means you can't blend in, you can't hide, you can't move through the world unnoticed. And that lack of invisibility is a vulnerability.", speaker: "J.", choices: [{ text: "Is that scary?", next: j2_9i }, { text: "Always aware?", next: j2_9j }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_9k = { text: "Both. Double the scrutiny, double the assumptions, double the stereotypes. People see my skin color and make assumptions about who I am, how I'll behave, whether I'm dangerous. Then they see my gender presentation and make another set of assumptions. Being Black and queer means navigating both sets of stereotypes simultaneously. The hypersexualization, the criminalization, the fear—all of it compounds.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_9l = { text: "Yeah, they compound in ways that are hard to explain. Being Black makes me hypervisible in certain spaces. Being queer makes me hypervisible in others. Being both means I'm rarely invisible anywhere. And those visibilities don't just add up—they multiply. Black queerness is read differently than white queerness. Black masculinity is read differently than white masculinity. The intersection creates its own specific experience of visibility and vulnerability.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_8f = { text: "Being Black and queer. Those two identities together create a specific kind of visibility. In white spaces, I'm visible as Black. In straight spaces, I'm visible as queer. In most spaces, I'm both. And that double visibility comes with double scrutiny. People are watching me, judging me, making assumptions about me based on both my race and my queerness. It's a lot to carry.", speaker: "J.", choices: [{ text: "Double visibility?", next: j2_9k }, { text: "Do they intersect?", next: j2_9l }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_7c = { text: "I'm hypervisible in most spaces I enter. As a Black person, I'm often one of few or the only one. As a visibly queer, masc-presenting person, I stand out. Those two things together—Black and queer—make me highly visible. People notice me. They stare. They make assumptions. That hypervisibility is exhausting and dangerous. I can't blend in. I can't go unnoticed.", speaker: "J.", choices: [{ text: "How does that affect safety?", next: j2_8e }, { text: "Because of what?", next: j2_8f }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_9m = { text: "Some people, yeah. But trust is earned slowly. I've been burned before by people I thought were safe—people who turned out to be performative allies or who didn't understand the specific challenges I face. So now I'm careful. I have a small circle of people I truly trust, people who've shown up for me consistently. But I don't let just anyone in anymore.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_9n = { text: "Yeah, I have to. Walls aren't about being closed off—they're about protection. I've learned that not everyone deserves access to all of me. Some people have earned that access. Others haven't. And until they do, I keep parts of myself guarded. It's self-preservation. It's how I avoid getting hurt, getting betrayed, getting exposed in ways that aren't safe.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_8g = { text: "I'm selective about who I let in because not everyone is safe. Some people are curious about me in ways that feel invasive. Some people want to be allies but don't do the work. Some people are outright hostile. So I've learned to be careful. To observe people before I trust them. To protect myself by being selective about who gets access to my full self.", speaker: "J.", choices: [{ text: "Do you have safe people?", next: j2_9m }, { text: "Walls up?", next: j2_9n }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_9o = { text: "Not often. Maybe with my closest friends in private spaces. But in public? Almost never. I'm always aware. Always tracking my surroundings. Always calculating risk. Relaxing fully would mean letting my guard down, and that feels too dangerous. So I stay alert. I stay ready. It's exhausting, but it's survival.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_9p = { text: "Yeah, it's exhausting. Living in a constant state of low-level vigilance takes a toll. It drains you. Some days I'm so tired from just being aware, from just navigating, that I don't have energy for anything else. But I don't have the luxury of stopping. Relaxing fully, letting my guard down—that's not safe. So I keep going. I rest when I can, but I never fully relax in public.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_8h = { text: "I don't fully relax in public because I can't afford to. Public spaces are unpredictable. I don't know who's around me, what their intentions are, how they'll respond to my presence. So I stay on guard. I keep my awareness up. I track my surroundings. Relaxing would mean being vulnerable, and being vulnerable in public as a Black queer person in the South—that's risky.", speaker: "J.", choices: [{ text: "Ever?", next: j2_9o }, { text: "That's exhausting.", next: j2_9p }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_7d = { text: "Trust is complicated for me because trust requires vulnerability, and vulnerability can be dangerous. I've learned to be careful about who I trust. Not everyone is safe. Not everyone has good intentions. Some people are performative. Some are invasive. Some are outright hostile. So I protect myself by being selective, by observing people carefully before I let them in.", speaker: "J.", choices: [{ text: "Why?", next: j2_8g }, { text: "Can you let your guard down?", next: j2_8h }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_6b = { text: "Being visible is complex because visibility brings both representation and risk. On one hand, I want to be visible. I want other Black queer folks to see me and know they're not alone. I want to claim space, to exist loudly. But visibility also makes me a target. It makes me vulnerable to harassment, violence, discrimination. So I'm constantly balancing—how visible can I afford to be?", speaker: "J.", choices: [{ text: "Tell me about that.", next: j2_7c }, { text: "How do you handle it?", next: j2_7d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_5a = { text: "Safety and visibility are linked because the more visible I am, the less safe I am. Visibility means being noticed, being seen, standing out. And for a Black queer person in the South, standing out can be dangerous. It invites scrutiny, assumptions, hostility. So I'm always navigating that tension—wanting to be visible, needing to stay safe. Those two things are often in conflict.", speaker: "J.", choices: [{ text: "How so?", next: j2_6a }, { text: "Explain.", next: j2_6b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_4a = { text: "Living here requires strategy because Knoxville isn't always safe for people like me. I have to think strategically about where I go, when I go there, how I present myself. I have to navigate racism and homophobia and the particular ways those show up in the South. Every decision—where to eat, where to shop, which spaces to enter—requires calculation. Strategy isn't optional. It's survival.", speaker: "J.", choices: [{ text: "What do you mean?", next: j2_5a }, { text: "Tell me.", next: j2_5a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_3a = { text: "Safety is always on my mind because it has to be. As a Black masc queer person in the South, I'm navigating multiple layers of potential danger every day. I can't take safety for granted. I can't assume spaces are welcoming or that people will treat me with respect. So I stay aware. I stay strategic. I think about safety constantly because the alternative—not thinking about it—could get me hurt.", speaker: "J.", choices: [{ text: "Why?", next: j2_4a }, { text: "How so?", next: j2_4a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j2_2a = { text: "Being visible has risks—real, tangible risks. When you're visibly Black, visibly queer, visibly gender non-conforming, you attract attention. Some of that attention is benign curiosity. Some of it is hostile. Some of it is dangerous. Visibility means you can't hide, you can't blend in, you can't move through the world unnoticed. And in places where being different is seen as threatening, that visibility becomes a vulnerability.", speaker: "J.", choices: [{ text: "What risks?", next: j2_3a }, { text: "Tell me more.", next: j2_3a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };

// Branch 3: 8 choices
const j3_9a = { text: "Both. They're completely inseparable for me. My experience of gender is shaped by my Blackness. My experience of Blackness is shaped by my gender and my queerness. I can't do masculinity the way white folks do it because I'm Black. I can't do Blackness the way straight folks do it because I'm queer. All of these identities inform and shape each other. They're braided together into something that can't be pulled apart.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_9b = { text: "Definitely. One absolutely informs the other. My Blackness shapes how I understand and express my masculinity. My queerness shapes how I navigate Blackness. My gender shapes how I experience both race and sexuality. They're not discrete categories I can separate out. They're woven together into the fabric of who I am. Pull on one thread and the whole thing shifts.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_8a = { text: "My Blackness fundamentally shapes my gender expression and experience. Black masculinity carries different meanings, different stereotypes, different dangers than white masculinity. The way I move through the world as a masc person is deeply influenced by being Black. People read my gender through the lens of my race. Those two things can't be disentangled. My gender is Black gender. My Blackness is gendered.", speaker: "J.", choices: [{ text: "They're connected?", next: j3_9a }, { text: "Do they intersect?", next: j3_9b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_9c = { text: "I can't separate who I am into neat categories. I'm not Black in one moment and queer in another and masc in another. I'm all of those things simultaneously, all the time. Trying to separate them would be like trying to un-braid a rope. They've been twisted together for so long that they've become one thing. One unified identity that's made up of all these parts.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_9d = { text: "Yeah, I'm whole as I am. All my identities together—that's the complete picture. That's me. I'm not fractured or fragmented. I'm not picking and choosing which parts of myself to show up with. I'm bringing all of it. My Blackness, my queerness, my masculinity, my Southern roots—all of it together makes me who I am. I'm whole.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_8b = { text: "All my identities matter equally. I'm not Black first and then queer. I'm not queer first and then Black. They're simultaneous. They're equally important. They all shape my experience of the world. Prioritizing one over the others would be dishonest. It would be denying parts of myself. So I hold all of them with equal weight, equal importance.", speaker: "J.", choices: [{ text: "Can't pick one?", next: j3_9c }, { text: "They're all you?", next: j3_9d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_7a = { text: "Identity is intersectional—that's not just theory for me, it's lived reality. I experience the world through the intersection of being Black and queer and masc. Those identities don't exist separately. They create something specific, something that's more than just the sum of its parts. Intersectionality means understanding that my Blackness shapes my queerness, my queerness shapes my gender, my gender shapes my Blackness. They're all interconnected.", speaker: "J.", choices: [{ text: "How so?", next: j3_8a }, { text: "What does that mean?", next: j3_8b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_9e = { text: "Representation matters because when I show up visibly as a Black masc queer person, I'm showing other people like me that we exist. That we're here. That we're not alone. And visibility matters because the world tries to erase us, to make us invisible, to deny our existence. So being visible—being loud, being present, being unapologetic—that's resistance. That's claiming space that the world tries to deny us.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_9f = { text: "Yeah, I want to be seen. Not in a superficial way, but in a deep, full, human way. I want people to see me—all of me. My Blackness, my queerness, my masculinity, my complexity. I want to be visible so that other Black queer folks know they're not alone. So that the world can't pretend we don't exist. Visibility is activism. It's survival. It's claiming humanity.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_8c = { text: "I exist loudly when I can because quiet existence feels like erasure. When I have the energy, when I feel safe enough, I show up fully. I don't shrink myself. I don't make myself palatable. I exist in my full complexity and humanity. That loudness—that refusal to be small—is how I claim space. It's how I push back against a world that wants me to be invisible or to fit into narrow boxes.", speaker: "J.", choices: [{ text: "Why is that important?", next: j3_9e }, { text: "Visibility as activism?", next: j3_9f }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_9g = { text: "I navigate it carefully by choosing when and where to be visible. I assess the risk. In some spaces—queer spaces, spaces where I have community—I can be loud, I can take up space. In other spaces—hostile spaces, unfamiliar spaces—I might dial it back. Not because I'm ashamed, but because I'm strategic. I'm balancing visibility with safety. It's a constant calculation.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_9h = { text: "Yeah, it's exhausting but necessary. The risk is real—visibility can lead to harassment, to violence, to being targeted. But invisibility has its own cost. Invisibility means erasure, means denying parts of myself, means living in fear. So I take the risk. I choose visibility even though it's hard, even though it's exhausting, because the alternative—hiding, shrinking, disappearing—feels like a slower kind of death.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_8d = { text: "Visibility can be dangerous—that's the reality. When you're visible as a Black queer person, you attract attention, and some of that attention is hostile. You become a target for harassment, for violence, for discrimination. But invisibility isn't the answer either. Staying hidden, staying quiet—that's its own kind of violence. So I navigate this tension constantly. Balancing visibility with safety. Choosing when to be loud and when to protect myself.", speaker: "J.", choices: [{ text: "How do you balance that?", next: j3_9g }, { text: "Worth the risk?", next: j3_9h }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_7b = { text: "I claim space when possible because space isn't freely given to people like me. Spaces are designed for white people, for straight people, for gender-conforming people. So when I enter a space as a Black masc queer person, I'm already disrupting expectations. Claiming space means refusing to apologize for that disruption. It means existing fully, loudly, unapologetically. It's an act of resistance.", speaker: "J.", choices: [{ text: "Why?", next: j3_8c }, { text: "Is that risky?", next: j3_8d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_6a = { text: "Being myself is political because in a world that wants me to be invisible, my existence is resistance. Every time I show up as a Black masc queer person, I'm making a political statement. I'm saying I have a right to exist, to take up space, to be seen. I'm challenging systems that want to erase me. Just by being myself—by refusing to hide, to shrink, to conform—I'm doing political work.", speaker: "J.", choices: [{ text: "How so?", next: j3_7a }, { text: "Tell me about that.", next: j3_7b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_9i = { text: "Yeah, we absolutely need each other. Community isn't just nice to have—it's survival. Other Black queer folks understand what I'm going through in ways that nobody else can. They get the specific challenges, the specific joys, the specific complexity of our lives. We support each other, we validate each other, we remind each other that we're not alone. Without that, I don't think I'd survive.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_9j = { text: "Definitely essential. Community is how I stay grounded, how I stay sane, how I remember my own humanity when the world tries to deny it. When I'm with my people—other Black queer folks who get it—I can exhale. I can be fully myself without explanation or justification. That's not just important, it's essential. It's what keeps me going.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_8e = { text: "Finding people like me is important because they're the only ones who truly understand this specific experience. Being Black and queer and masc—that's a particular intersection that comes with particular challenges and joys. People who live at that same intersection get it without explanation. We share a language, a set of experiences, an understanding. That connection is invaluable. It's what makes survival possible.", speaker: "J.", choices: [{ text: "For support?", next: j3_9i }, { text: "Is community crucial?", next: j3_9j }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_9k = { text: "Online mostly—there are Black queer communities on social media where we find each other, support each other, share resources. And some local folks too. There's a small group of us here in Knoxville who've connected. We're not a huge community, but we're real. We show up for each other. We create pockets of safety and joy for each other. It's scattered but it's there.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_9l = { text: "Yeah, it takes effort. It's not like community just appears. You have to seek it out, build it deliberately. Especially here in Knoxville where there aren't a lot of us. So I reach out online. I go to events. I connect with people through friends of friends. I build community intentionally because it doesn't just happen organically in a place like this.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_8f = { text: "I seek out community actively and deliberately. I look for Black queer spaces online. I travel to bigger cities when I can to connect with larger communities. I reach out to people, build relationships intentionally. Community doesn't just happen—especially not here in Knoxville. You have to create it. You have to build it. And I do that work because community is what makes survival possible.", speaker: "J.", choices: [{ text: "Where do you find it?", next: j3_9k }, { text: "Is it hard to find?", next: j3_9l }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_7c = { text: "Community sustains me in ways nothing else can. When I'm with my people—other Black queer folks—I can be fully myself. I don't have to explain, justify, or defend my existence. I can just be. And that's sustaining. That's what keeps me going when the world feels hostile. Community reminds me I'm not alone, I'm not crazy, and I have a right to exist fully and joyfully.", speaker: "J.", choices: [{ text: "Why is that?", next: j3_8e }, { text: "How do you build it?", next: j3_8f }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_9m = { text: "Black joy is resistance because the world expects Black people to suffer. It expects us to be traumatized, oppressed, struggling. When I choose joy—when I laugh, when I love, when I celebrate my Blackness and my queerness—I'm resisting that narrative. I'm saying I'm more than my trauma. I'm claiming happiness and pleasure as my right. That's radical. That's resistance.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_9n = { text: "Yeah, just existing is radical. In a world that wants to erase Black queer people, that wants us to be invisible or to fit into narrow acceptable boxes, showing up fully as myself is a radical act. I don't have to be an activist or an organizer to be doing political work. Just living, just existing loudly in my full humanity—that's resistance. That's radical.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_8g = { text: "Being myself is an act of resistance because the world wants me to be something else. It wants me to be quieter, smaller, more palatable. It wants me to hide my Blackness or my queerness or my masculinity. But I refuse. I show up as my full self—complex, loud, unapologetic. That refusal to shrink, that insistence on my full humanity—that's resistance. It's fighting back just by existing.", speaker: "J.", choices: [{ text: "How so?", next: j3_9m }, { text: "Existence as resistance?", next: j3_9n }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_9o = { text: "I choose joy when I can. Despite all the struggle, despite the exhaustion, despite the constant navigation—I refuse to let that be the only story. I find joy in my community, in my identity, in small moments of beauty and connection. Joy is my resistance. It's how I claim my full humanity. It's how I remind myself that I'm alive, not just surviving.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_9p = { text: "Yeah, despite everything. Despite the racism, the homophobia, the danger, the exhaustion—I still claim joy. I still laugh, I still love, I still find beauty in my life and in my community. That joy is defiant. It's saying that the systems trying to crush me haven't won. I'm still here. I'm still whole. I'm still capable of happiness. And that's powerful.", speaker: "J.", choices: [{ text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_8h = { text: "I refuse to be defined by struggle alone. Yes, I struggle. Yes, being Black and queer and masc in the South is hard. But I'm more than that hardship. I'm also joy, love, creativity, community, laughter, beauty. If I let struggle be the only narrative, I'm letting the systems that oppress me win. So I claim my full humanity, which includes both the struggle and the joy.", speaker: "J.", choices: [{ text: "What else defines you?", next: j3_9o }, { text: "You claim joy?", next: j3_9p }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_7d = { text: "My existence is more than survival. Yes, survival matters. Yes, I have to navigate safety and risk constantly. But I'm not just surviving—I'm living. I'm building community. I'm finding joy. I'm creating meaning. I'm claiming my full humanity. Survival is the baseline, but I want more than that. I want to thrive. I want to live fully, not just make it through each day.", speaker: "J.", choices: [{ text: "What is it?", next: j3_8g }, { text: "Tell me more.", next: j3_8h }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_6b = { text: "I claim my full humanity by refusing to be reduced to stereotypes or single-issue identities. I'm complex. I contain multitudes. I'm Black and queer and masc and Southern and more. I'm all of that at once. And I deserve to be seen and treated as fully human—with dignity, respect, complexity. Claiming my full humanity means insisting on that. It means refusing to be flattened or simplified.", speaker: "J.", choices: [{ text: "Through community?", next: j3_7c }, { text: "What does that mean?", next: j3_7d }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_5a = { text: "My identity is political because who I am challenges dominant systems. Being Black challenges white supremacy. Being queer challenges heteronormativity. Being masc and assigned female at birth challenges the gender binary. I don't have to be an activist for my identity to be political—it just is. My existence disrupts systems that want to maintain the status quo. So identity and politics are inseparable for me.", speaker: "J.", choices: [{ text: "How so?", next: j3_6a }, { text: "Tell me.", next: j3_6b }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_4a = { text: "Being myself matters because my existence is resistance. In a world that wants to erase Black queer people, showing up as my full self is a political act. It's claiming space, claiming humanity, claiming the right to exist. Being myself matters not just for me, but for other people like me who need to see that we're here, that we're real, that we have a right to exist fully and joyfully.", speaker: "J.", choices: [{ text: "Why?", next: j3_5a }, { text: "How so?", next: j3_5a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_3a = { text: "Identity is complex because it's not just one thing. I'm not just Black or just queer or just masc. I'm all of those things simultaneously, and they intersect and inform each other in ways that are sometimes hard to articulate. That complexity is important. It's what makes me who I am. And understanding that complexity—holding space for it—is essential to understanding my experience.", speaker: "J.", choices: [{ text: "Tell me about that.", next: j3_4a }, { text: "Explain.", next: j3_4a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };
const j3_2a = { text: "There's a lot to who I am—layers and intersections that make me complex. I'm Black, I'm queer, I'm masc, I'm from the South. All of those things shape my experience. They create a specific lens through which I see and navigate the world. Understanding who I am means understanding all of those pieces together, not trying to separate them out or prioritize one over the others.", speaker: "J.", choices: [{ text: "Like what?", next: j3_3a }, { text: "Tell me more.", next: j3_3a }, { text: getRandomExitLine(), next: exitNode }, { text: getRandomRestartLine(), next: restartMarker }] };

export const joceDialogue = {
  text: "I'm J. I'm Black, masc presenting, and navigating all of that here in Knoxville. It's...a lot sometimes.",
  speaker: "J.",
  choices: [
    { text: "Tell me about navigating labels and expectations.", next: j1_2a },
    { text: "What's it like being visible here?", next: j2_2a },
    { text: "How does identity and community intersect for you?", next: j3_2a },
    { text: getRandomExitLine(), next: exitNode }
  ]
};
