/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tfjbhtriagbdursqylti"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmamJodHJpYWdiZHVyc3F5bHRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwOTU5ODMsImV4cCI6MjA5MDY3MTk4M30.c-3D9DmsTlD-GUCS6HP74_pMaa8ZEkGATuVr_4WoKEc"